# Generated by Django 4.2.1 on 2023-05-24 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coustmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('photo', models.ImageField(null=True, upload_to='photos')),
                ('PhonNumber', models.CharField(max_length=16, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(blank=True, default='', max_length=10)),
                ('contackt_person_numer', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.CharField(blank=True, default='', max_length=10)),
                ('latitude', models.CharField(blank=True, default='', max_length=10)),
                ('longitude', models.CharField(blank=True, default='', max_length=10)),
                ('address_type', models.CharField(blank=True, default='', max_length=10)),
                ('address_coustem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoustemSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
                ('Coustmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceName', models.CharField(max_length=10)),
                ('price', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ohdat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateField(auto_now=True)),
                ('order_status', models.BooleanField(default=False)),
                ('orderType', models.IntegerField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=100)),
                ('payment_status', models.IntegerField(blank=True)),
                ('payment_method', models.IntegerField(blank=True)),
                ('ordersTotalPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_amount', models.IntegerField(blank=True)),
                ('delivery_Employe', models.CharField(blank=True, default='', max_length=10)),
                ('coustmerId_owner_of_prodect', models.IntegerField(blank=True)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address')),
            ],
        ),
        migrations.CreateModel(
            name='Prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namepasnes', models.CharField(help_text='الاسم التجاري', max_length=20, null=True)),
                ('namescient', models.CharField(help_text='الاسم العلمي', max_length=20, null=True)),
                ('manufactureCompany', models.CharField(help_text='الشركة المصنعة', max_length=20, null=True)),
                ('desc', models.CharField(help_text='وصف المنتج', max_length=10)),
                ('quntity', models.CharField(help_text='كمية المنتج', max_length=10)),
                ('price', models.CharField(help_text='سعر المنتج', max_length=10)),
                ('Created_at', models.CharField(help_text='تاريخ انشاء المنتج', max_length=10)),
                ('dataFinshProdect', models.CharField(help_text='تارخ انتهاء المنتج', max_length=10)),
                ('photo', models.ImageField(null=True, upload_to='photos')),
                ('ChoisPrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.myprice')),
                ('coustemCatogry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.coustemsections')),
                ('prodect_CoustmerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameType', models.CharField(blank=True, max_length=15, null=True)),
                ('desc', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='productOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOffers', models.CharField(help_text='اسم العرض', max_length=20)),
                ('items_discount', models.CharField(help_text=' نسبة الخصم', max_length=10)),
                ('price_after_discount', models.FloatField(help_text=' سعر البيع بعد الخصم', max_length=10, null=True)),
                ('offers_prodectIid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.prodect')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMthods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('p_CoustmerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quntity', models.IntegerField(blank=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateTimeField(blank=True)),
                ('Prodect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.prodect')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_Detiels',
            field=models.ManyToManyField(through='account.OrderDetails', to='account.prodect'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_coustmerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myprice',
            name='ohde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ohdat'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('favorite_coustemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorite_prodectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.prodect')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(blank=True)),
                ('cart_coustemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cart_prodectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.prodect')),
            ],
        ),
        migrations.AddField(
            model_name='coustmer',
            name='TypeUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.typeaccount'),
        ),
    ]
